---

# Charts release configuration file example
# This file is used to update the version of the helm charts and images in the values.yaml file
# It is used in the helm-charts-release action
# ${release} is replaced with the release version provided in the workflow

charts:
  - name: qubership-zookeeper
    chart_file: charts/helm/zookeeper-service/Chart.yaml
    values_file: charts/helm/zookeeper-service/values.yaml
    image:
      - ghcr.io/netcracker/qubership-zookeeper-operator:${release}
      - ghcr.io/netcracker/qubership-docker-zookeeper:${release}
      - ghcr.io/netcracker/qubership-zookeeper-monitoring:${release}
      - ghcr.io/netcracker/qubership-zookeeper-backup-daemon:${release}
      - ghcr.io/netcracker/qubership-zookeeper-integration-tests:${release}